USE [master]
GO

/****** Object:  Database [DFNB]    Script Date: 11/4/2020 4:47:14 PM ******/
CREATE DATABASE [DFNB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DFNB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DFNB.mdf' , SIZE = 1324032KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DFNB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DFNB_log.ldf' , SIZE = 1437888KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DFNB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DFNB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DFNB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DFNB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DFNB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DFNB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DFNB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DFNB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DFNB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DFNB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DFNB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DFNB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DFNB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DFNB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DFNB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DFNB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DFNB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DFNB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DFNB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DFNB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DFNB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DFNB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DFNB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DFNB] SET RECOVERY FULL 
GO

ALTER DATABASE [DFNB] SET  MULTI_USER 
GO

ALTER DATABASE [DFNB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DFNB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DFNB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DFNB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DFNB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DFNB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DFNB] SET  READ_WRITE 
GO


